apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daybreak-tenant-app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: daybreak-tenant
  source:
    path: patch-me-see-overlays
    repoURL: patch-me-see-tenant-overlays
    targetRevision: patch-me-see-tenant-overlays
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
