apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crunchy-psql
spec:
  destination:
    namespace: daybreak-gitops
    server: https://kubernetes.default.svc
  project: shared-services
  source:
    path: components/argocd/shared-services/crunchy/overlays/default
    repoURL: https://github.com/redhat-guidehouse-daybreak/openshif-cluster-bootstrap-gitops.git
    targetRevision: vapo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - Replace=false
      - CreateNamespace=true