apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: 3scale-app
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'