apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3scale-app
spec:
  destination:
    namespace: 3scale
    server: https://kubernetes.default.svc
  project: 3scale-app
  source:
    path: tenant/daybreak/components/3scale/overlay/default
    repoURL: patch-me-see-tenant-overlays
    targetRevision: patch-me-see-tenant-overlays
  syncPolicy:
    automated:
      prune: false
      selfHeal: true