apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: 3scale-developer-user-secret
spec:
  encryptedData:
    password: AgABiBz/yeDp+8pWE11JuHnxMPODEXf9BaFM3nHwFeExDd0YOUG9eFZjWq2vvuhrKcm90yydjDjopeQJLSmt4B+iI1+6rS5fKZo0fsfir1ksoO7vbUWs9lFP4A/8To+PbvKwI2zoSXhsoboeB/aAq/DnmM2YjGIAzGYQKWMXASt6038zbl8czw/Fsv/0yA/JurwhG25FjDdWOjGTxBzuHzy2VMnlJiCrltwlm28RJRAGQDb0VRKR74uRslFrjRAnAG8nq9B6V0aXABlrI8Wp7TdVZXuTUi30bYWMK9prSjp2SEhgDx9vvMz4VQ/vrwF8/0fTqliJLlxr1H+lIDC5/bLpe0NVvWWL5WWGdsM4wJS56C5m2Aj3A90sk4h6adWHP/tK0ahx+5EzF3p2y7W6WDX7uBM2cVLnqxOuPq7y1ARs3p755fZQg6eHo4kaLvugyN6Tj4zkotQq3iyvRnUtBF2Vk6392GU+uVK78zpCuwQsUCp6odJVH7ha2sub+hLdEW3mG+IZf9kplnWVN2yshvC39DLSwm2VdfqKSXasamxPoPmyj6vuDe4Fx/fi3PoIQHuxazAIw7yFgfsfBeHXb7XdJXlQLPfmYGEXfCxfM5Gux4scoSjib/2IEiGF7qK+eNGQ1IvUOL6iSyt5JZTokWBmG52HOkm6IrGmU3a9bXSYb39yL/rfNZswUvN43JkQSXNBoIyPl2Sm9T8=
  template:
    metadata:
      creationTimestamp: null
      name: 3scale-developer-user-secret
